apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: productcatalog-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aneenamathew123/Cloud-native-microservices-DevOps.git
    targetRevision: main
    path: kubernetes-manifests/product-catalog
  destination:
    server: https://kubernetes.default.svc
    namespace: dev                          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true